import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import "./global.css";

const switzerFont = localFont({
  src: [
    {
      path: './fonts/switzer-variable.woff2',
      style: 'normal',
    },
    {
      path: './fonts/switzer-variable-italic.woff2',
      style: 'italic',
    },
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={switzerFont.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
